import ContactList from 'c/contactList';

describe('c-contact-list', () => {
    afterEach(() => {
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        const element = createElement('c-contact-list', {
            is: ContactList
        });

        document.body.appendChild(element);
        expect(1).toBe(1);
    });
});